//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameObject2LuaTablePairWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(System.Collections.Generic.KeyValuePair<UnityEngine.GameObject,LuaInterface.LuaTable>), null, "GameObject2LuaTablePair");
		L.RegFunction("ToString", ToString);
		L.RegFunction("New", _CreateGameObject2LuaTablePair);
		L.RegFunction("__tostring", Lua_ToString);
		L.RegVar("Key", get_Key, null);
		L.RegVar("Value", get_Value, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateGameObject2LuaTablePair(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckUnityObject(L, 1, typeof(UnityEngine.GameObject));
				LuaTable arg1 = ToLua.CheckLuaTable(L, 2);
				System.Collections.Generic.KeyValuePair<UnityEngine.GameObject,LuaInterface.LuaTable> obj = new System.Collections.Generic.KeyValuePair<UnityEngine.GameObject,LuaInterface.LuaTable>(arg0, arg1);
				ToLua.PushValue(L, obj);
				return 1;
			}
			else if (count == 0)
			{
				System.Collections.Generic.KeyValuePair<UnityEngine.GameObject,LuaInterface.LuaTable> obj = new System.Collections.Generic.KeyValuePair<UnityEngine.GameObject,LuaInterface.LuaTable>();
				ToLua.PushValue(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: System.Collections.Generic.KeyValuePair<UnityEngine.GameObject,LuaInterface.LuaTable>.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ToString(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.Collections.Generic.KeyValuePair<UnityEngine.GameObject,LuaInterface.LuaTable> obj = (System.Collections.Generic.KeyValuePair<UnityEngine.GameObject,LuaInterface.LuaTable>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.KeyValuePair<UnityEngine.GameObject,LuaInterface.LuaTable>));
			string o = obj.ToString();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Key(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			System.Collections.Generic.KeyValuePair<UnityEngine.GameObject,LuaInterface.LuaTable> obj = (System.Collections.Generic.KeyValuePair<UnityEngine.GameObject,LuaInterface.LuaTable>)o;
			UnityEngine.GameObject ret = obj.Key;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Key on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Value(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			System.Collections.Generic.KeyValuePair<UnityEngine.GameObject,LuaInterface.LuaTable> obj = (System.Collections.Generic.KeyValuePair<UnityEngine.GameObject,LuaInterface.LuaTable>)o;
			LuaInterface.LuaTable ret = obj.Value;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Value on a nil value" : e.Message);
		}
	}
}

