//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ProjectConfigUtilityWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("ProjectConfigUtility");
		L.RegFunction("GetProjectConfig", GetProjectConfig);
		L.RegVar("ConfigFileName", get_ConfigFileName, null);
		L.RegVar("ConfigFilePostfix", get_ConfigFilePostfix, null);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetProjectConfig(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			XYHY.ProjectConfigInfo o = ProjectConfigUtility.GetProjectConfig();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ConfigFileName(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, ProjectConfigUtility.ConfigFileName);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ConfigFilePostfix(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, ProjectConfigUtility.ConfigFilePostfix);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

