//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class System_Collections_Generic_List_UnityEngine_MaterialWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(System.Collections.Generic.List<UnityEngine.Material>), typeof(System.Object), "List_UnityEngine_Material");
		L.RegFunction("Add", Add);
		L.RegFunction("AddRange", AddRange);
		L.RegFunction("AsReadOnly", AsReadOnly);
		L.RegFunction("BinarySearch", BinarySearch);
		L.RegFunction("Clear", Clear);
		L.RegFunction("Contains", Contains);
		L.RegFunction("CopyTo", CopyTo);
		L.RegFunction("Exists", Exists);
		L.RegFunction("Find", Find);
		L.RegFunction("FindAll", FindAll);
		L.RegFunction("FindIndex", FindIndex);
		L.RegFunction("FindLast", FindLast);
		L.RegFunction("FindLastIndex", FindLastIndex);
		L.RegFunction("ForEach", ForEach);
		L.RegFunction("GetEnumerator", GetEnumerator);
		L.RegFunction("GetRange", GetRange);
		L.RegFunction("IndexOf", IndexOf);
		L.RegFunction("Insert", Insert);
		L.RegFunction("InsertRange", InsertRange);
		L.RegFunction("LastIndexOf", LastIndexOf);
		L.RegFunction("Remove", Remove);
		L.RegFunction("RemoveAll", RemoveAll);
		L.RegFunction("RemoveAt", RemoveAt);
		L.RegFunction("RemoveRange", RemoveRange);
		L.RegFunction("Reverse", Reverse);
		L.RegFunction("Sort", Sort);
		L.RegFunction("ToArray", ToArray);
		L.RegFunction("TrimExcess", TrimExcess);
		L.RegFunction("TrueForAll", TrueForAll);
		L.RegFunction("get_Item", get_Item);
		L.RegFunction("set_Item", set_Item);
		L.RegFunction("New", _CreateSystem_Collections_Generic_List_UnityEngine_Material);
		L.RegVar("this", _this, null);
		L.RegFunction("__tostring", Lua_ToString);
		L.RegVar("Capacity", get_Capacity, set_Capacity);
		L.RegVar("Count", get_Count, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSystem_Collections_Generic_List_UnityEngine_Material(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = new System.Collections.Generic.List<UnityEngine.Material>();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1 && TypeChecker.CheckTypes(L, 1, typeof(int)))
			{
				int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
				System.Collections.Generic.List<UnityEngine.Material> obj = new System.Collections.Generic.List<UnityEngine.Material>(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.IEnumerable<UnityEngine.Material>)))
			{
				System.Collections.Generic.IEnumerable<UnityEngine.Material> arg0 = (System.Collections.Generic.IEnumerable<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.IEnumerable<UnityEngine.Material>));
				System.Collections.Generic.List<UnityEngine.Material> obj = new System.Collections.Generic.List<UnityEngine.Material>(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: System.Collections.Generic.List<UnityEngine.Material>.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _get_this(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			UnityEngine.Material o = obj[arg0];
			ToLua.Push(L, o);
			return 1;

		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _set_this(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			UnityEngine.Material arg1 = (UnityEngine.Material)ToLua.CheckUnityObject(L, 3, typeof(UnityEngine.Material));
			obj[arg0] = arg1;
			return 0;

		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _this(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushvalue(L, 1);
			LuaDLL.tolua_bindthis(L, _get_this, _set_this);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Add(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			UnityEngine.Material arg0 = (UnityEngine.Material)ToLua.CheckUnityObject(L, 2, typeof(UnityEngine.Material));
			obj.Add(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddRange(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			System.Collections.Generic.IEnumerable<UnityEngine.Material> arg0 = (System.Collections.Generic.IEnumerable<UnityEngine.Material>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.IEnumerable<UnityEngine.Material>));
			obj.AddRange(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AsReadOnly(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			System.Collections.ObjectModel.ReadOnlyCollection<UnityEngine.Material> o = obj.AsReadOnly();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int BinarySearch(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>), typeof(UnityEngine.Material)))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				UnityEngine.Material arg0 = (UnityEngine.Material)ToLua.ToObject(L, 2);
				int o = obj.BinarySearch(arg0);
				LuaDLL.lua_pushinteger(L, o);
				return 1;
			}
			else if (count == 3 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>), typeof(UnityEngine.Material), typeof(System.Collections.Generic.IComparer<UnityEngine.Material>)))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				UnityEngine.Material arg0 = (UnityEngine.Material)ToLua.ToObject(L, 2);
				System.Collections.Generic.IComparer<UnityEngine.Material> arg1 = (System.Collections.Generic.IComparer<UnityEngine.Material>)ToLua.ToObject(L, 3);
				int o = obj.BinarySearch(arg0, arg1);
				LuaDLL.lua_pushinteger(L, o);
				return 1;
			}
			else if (count == 5 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>), typeof(int), typeof(int), typeof(UnityEngine.Material), typeof(System.Collections.Generic.IComparer<UnityEngine.Material>)))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				UnityEngine.Material arg2 = (UnityEngine.Material)ToLua.ToObject(L, 4);
				System.Collections.Generic.IComparer<UnityEngine.Material> arg3 = (System.Collections.Generic.IComparer<UnityEngine.Material>)ToLua.ToObject(L, 5);
				int o = obj.BinarySearch(arg0, arg1, arg2, arg3);
				LuaDLL.lua_pushinteger(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: System.Collections.Generic.List<UnityEngine.Material>.BinarySearch");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Clear(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			obj.Clear();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Contains(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			UnityEngine.Material arg0 = (UnityEngine.Material)ToLua.CheckUnityObject(L, 2, typeof(UnityEngine.Material));
			bool o = obj.Contains(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CopyTo(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>), typeof(UnityEngine.Material[])))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				UnityEngine.Material[] arg0 = ToLua.CheckObjectArray<UnityEngine.Material>(L, 2);
				obj.CopyTo(arg0);
				return 0;
			}
			else if (count == 3 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>), typeof(UnityEngine.Material[]), typeof(int)))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				UnityEngine.Material[] arg0 = ToLua.CheckObjectArray<UnityEngine.Material>(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				obj.CopyTo(arg0, arg1);
				return 0;
			}
			else if (count == 5 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>), typeof(int), typeof(UnityEngine.Material[]), typeof(int), typeof(int)))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				UnityEngine.Material[] arg1 = ToLua.CheckObjectArray<UnityEngine.Material>(L, 3);
				int arg2 = (int)LuaDLL.lua_tonumber(L, 4);
				int arg3 = (int)LuaDLL.lua_tonumber(L, 5);
				obj.CopyTo(arg0, arg1, arg2, arg3);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: System.Collections.Generic.List<UnityEngine.Material>.CopyTo");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Exists(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			System.Predicate<UnityEngine.Material> arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (System.Predicate<UnityEngine.Material>)ToLua.CheckObject(L, 2, typeof(System.Predicate<UnityEngine.Material>));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(System.Predicate<UnityEngine.Material>), func) as System.Predicate<UnityEngine.Material>;
			}

			bool o = obj.Exists(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Find(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			System.Predicate<UnityEngine.Material> arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (System.Predicate<UnityEngine.Material>)ToLua.CheckObject(L, 2, typeof(System.Predicate<UnityEngine.Material>));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(System.Predicate<UnityEngine.Material>), func) as System.Predicate<UnityEngine.Material>;
			}

			UnityEngine.Material o = obj.Find(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FindAll(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			System.Predicate<UnityEngine.Material> arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (System.Predicate<UnityEngine.Material>)ToLua.CheckObject(L, 2, typeof(System.Predicate<UnityEngine.Material>));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(System.Predicate<UnityEngine.Material>), func) as System.Predicate<UnityEngine.Material>;
			}

			System.Collections.Generic.List<UnityEngine.Material> o = obj.FindAll(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FindIndex(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>), typeof(System.Predicate<UnityEngine.Material>)))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				System.Predicate<UnityEngine.Material> arg0 = null;
				LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

				if (funcType2 != LuaTypes.LUA_TFUNCTION)
				{
					 arg0 = (System.Predicate<UnityEngine.Material>)ToLua.ToObject(L, 2);
				}
				else
				{
					LuaFunction func = ToLua.ToLuaFunction(L, 2);
					arg0 = DelegateFactory.CreateDelegate(typeof(System.Predicate<UnityEngine.Material>), func) as System.Predicate<UnityEngine.Material>;
				}

				int o = obj.FindIndex(arg0);
				LuaDLL.lua_pushinteger(L, o);
				return 1;
			}
			else if (count == 3 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>), typeof(int), typeof(System.Predicate<UnityEngine.Material>)))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				System.Predicate<UnityEngine.Material> arg1 = null;
				LuaTypes funcType3 = LuaDLL.lua_type(L, 3);

				if (funcType3 != LuaTypes.LUA_TFUNCTION)
				{
					 arg1 = (System.Predicate<UnityEngine.Material>)ToLua.ToObject(L, 3);
				}
				else
				{
					LuaFunction func = ToLua.ToLuaFunction(L, 3);
					arg1 = DelegateFactory.CreateDelegate(typeof(System.Predicate<UnityEngine.Material>), func) as System.Predicate<UnityEngine.Material>;
				}

				int o = obj.FindIndex(arg0, arg1);
				LuaDLL.lua_pushinteger(L, o);
				return 1;
			}
			else if (count == 4 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>), typeof(int), typeof(int), typeof(System.Predicate<UnityEngine.Material>)))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				System.Predicate<UnityEngine.Material> arg2 = null;
				LuaTypes funcType4 = LuaDLL.lua_type(L, 4);

				if (funcType4 != LuaTypes.LUA_TFUNCTION)
				{
					 arg2 = (System.Predicate<UnityEngine.Material>)ToLua.ToObject(L, 4);
				}
				else
				{
					LuaFunction func = ToLua.ToLuaFunction(L, 4);
					arg2 = DelegateFactory.CreateDelegate(typeof(System.Predicate<UnityEngine.Material>), func) as System.Predicate<UnityEngine.Material>;
				}

				int o = obj.FindIndex(arg0, arg1, arg2);
				LuaDLL.lua_pushinteger(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: System.Collections.Generic.List<UnityEngine.Material>.FindIndex");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FindLast(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			System.Predicate<UnityEngine.Material> arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (System.Predicate<UnityEngine.Material>)ToLua.CheckObject(L, 2, typeof(System.Predicate<UnityEngine.Material>));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(System.Predicate<UnityEngine.Material>), func) as System.Predicate<UnityEngine.Material>;
			}

			UnityEngine.Material o = obj.FindLast(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FindLastIndex(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>), typeof(System.Predicate<UnityEngine.Material>)))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				System.Predicate<UnityEngine.Material> arg0 = null;
				LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

				if (funcType2 != LuaTypes.LUA_TFUNCTION)
				{
					 arg0 = (System.Predicate<UnityEngine.Material>)ToLua.ToObject(L, 2);
				}
				else
				{
					LuaFunction func = ToLua.ToLuaFunction(L, 2);
					arg0 = DelegateFactory.CreateDelegate(typeof(System.Predicate<UnityEngine.Material>), func) as System.Predicate<UnityEngine.Material>;
				}

				int o = obj.FindLastIndex(arg0);
				LuaDLL.lua_pushinteger(L, o);
				return 1;
			}
			else if (count == 3 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>), typeof(int), typeof(System.Predicate<UnityEngine.Material>)))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				System.Predicate<UnityEngine.Material> arg1 = null;
				LuaTypes funcType3 = LuaDLL.lua_type(L, 3);

				if (funcType3 != LuaTypes.LUA_TFUNCTION)
				{
					 arg1 = (System.Predicate<UnityEngine.Material>)ToLua.ToObject(L, 3);
				}
				else
				{
					LuaFunction func = ToLua.ToLuaFunction(L, 3);
					arg1 = DelegateFactory.CreateDelegate(typeof(System.Predicate<UnityEngine.Material>), func) as System.Predicate<UnityEngine.Material>;
				}

				int o = obj.FindLastIndex(arg0, arg1);
				LuaDLL.lua_pushinteger(L, o);
				return 1;
			}
			else if (count == 4 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>), typeof(int), typeof(int), typeof(System.Predicate<UnityEngine.Material>)))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				System.Predicate<UnityEngine.Material> arg2 = null;
				LuaTypes funcType4 = LuaDLL.lua_type(L, 4);

				if (funcType4 != LuaTypes.LUA_TFUNCTION)
				{
					 arg2 = (System.Predicate<UnityEngine.Material>)ToLua.ToObject(L, 4);
				}
				else
				{
					LuaFunction func = ToLua.ToLuaFunction(L, 4);
					arg2 = DelegateFactory.CreateDelegate(typeof(System.Predicate<UnityEngine.Material>), func) as System.Predicate<UnityEngine.Material>;
				}

				int o = obj.FindLastIndex(arg0, arg1, arg2);
				LuaDLL.lua_pushinteger(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: System.Collections.Generic.List<UnityEngine.Material>.FindLastIndex");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ForEach(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			System.Action<UnityEngine.Material> arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (System.Action<UnityEngine.Material>)ToLua.CheckObject(L, 2, typeof(System.Action<UnityEngine.Material>));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(System.Action<UnityEngine.Material>), func) as System.Action<UnityEngine.Material>;
			}

			obj.ForEach(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetEnumerator(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			System.Collections.Generic.List<UnityEngine.Material>.Enumerator o = obj.GetEnumerator();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetRange(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			System.Collections.Generic.List<UnityEngine.Material> o = obj.GetRange(arg0, arg1);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IndexOf(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>), typeof(UnityEngine.Material)))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				UnityEngine.Material arg0 = (UnityEngine.Material)ToLua.ToObject(L, 2);
				int o = obj.IndexOf(arg0);
				LuaDLL.lua_pushinteger(L, o);
				return 1;
			}
			else if (count == 3 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>), typeof(UnityEngine.Material), typeof(int)))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				UnityEngine.Material arg0 = (UnityEngine.Material)ToLua.ToObject(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				int o = obj.IndexOf(arg0, arg1);
				LuaDLL.lua_pushinteger(L, o);
				return 1;
			}
			else if (count == 4 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>), typeof(UnityEngine.Material), typeof(int), typeof(int)))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				UnityEngine.Material arg0 = (UnityEngine.Material)ToLua.ToObject(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				int arg2 = (int)LuaDLL.lua_tonumber(L, 4);
				int o = obj.IndexOf(arg0, arg1, arg2);
				LuaDLL.lua_pushinteger(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: System.Collections.Generic.List<UnityEngine.Material>.IndexOf");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Insert(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			UnityEngine.Material arg1 = (UnityEngine.Material)ToLua.CheckUnityObject(L, 3, typeof(UnityEngine.Material));
			obj.Insert(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InsertRange(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			System.Collections.Generic.IEnumerable<UnityEngine.Material> arg1 = (System.Collections.Generic.IEnumerable<UnityEngine.Material>)ToLua.CheckObject(L, 3, typeof(System.Collections.Generic.IEnumerable<UnityEngine.Material>));
			obj.InsertRange(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LastIndexOf(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>), typeof(UnityEngine.Material)))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				UnityEngine.Material arg0 = (UnityEngine.Material)ToLua.ToObject(L, 2);
				int o = obj.LastIndexOf(arg0);
				LuaDLL.lua_pushinteger(L, o);
				return 1;
			}
			else if (count == 3 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>), typeof(UnityEngine.Material), typeof(int)))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				UnityEngine.Material arg0 = (UnityEngine.Material)ToLua.ToObject(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				int o = obj.LastIndexOf(arg0, arg1);
				LuaDLL.lua_pushinteger(L, o);
				return 1;
			}
			else if (count == 4 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>), typeof(UnityEngine.Material), typeof(int), typeof(int)))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				UnityEngine.Material arg0 = (UnityEngine.Material)ToLua.ToObject(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				int arg2 = (int)LuaDLL.lua_tonumber(L, 4);
				int o = obj.LastIndexOf(arg0, arg1, arg2);
				LuaDLL.lua_pushinteger(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: System.Collections.Generic.List<UnityEngine.Material>.LastIndexOf");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Remove(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			UnityEngine.Material arg0 = (UnityEngine.Material)ToLua.CheckUnityObject(L, 2, typeof(UnityEngine.Material));
			bool o = obj.Remove(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveAll(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			System.Predicate<UnityEngine.Material> arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (System.Predicate<UnityEngine.Material>)ToLua.CheckObject(L, 2, typeof(System.Predicate<UnityEngine.Material>));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(System.Predicate<UnityEngine.Material>), func) as System.Predicate<UnityEngine.Material>;
			}

			int o = obj.RemoveAll(arg0);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveAt(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.RemoveAt(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveRange(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			obj.RemoveRange(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Reverse(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>)))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				obj.Reverse();
				return 0;
			}
			else if (count == 3 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>), typeof(int), typeof(int)))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				obj.Reverse(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: System.Collections.Generic.List<UnityEngine.Material>.Reverse");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Sort(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>)))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				obj.Sort();
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>), typeof(System.Comparison<UnityEngine.Material>)))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				System.Comparison<UnityEngine.Material> arg0 = null;
				LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

				if (funcType2 != LuaTypes.LUA_TFUNCTION)
				{
					 arg0 = (System.Comparison<UnityEngine.Material>)ToLua.ToObject(L, 2);
				}
				else
				{
					LuaFunction func = ToLua.ToLuaFunction(L, 2);
					arg0 = DelegateFactory.CreateDelegate(typeof(System.Comparison<UnityEngine.Material>), func) as System.Comparison<UnityEngine.Material>;
				}

				obj.Sort(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>), typeof(System.Collections.Generic.IComparer<UnityEngine.Material>)))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				System.Collections.Generic.IComparer<UnityEngine.Material> arg0 = (System.Collections.Generic.IComparer<UnityEngine.Material>)ToLua.ToObject(L, 2);
				obj.Sort(arg0);
				return 0;
			}
			else if (count == 4 && TypeChecker.CheckTypes(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>), typeof(int), typeof(int), typeof(System.Collections.Generic.IComparer<UnityEngine.Material>)))
			{
				System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.ToObject(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				System.Collections.Generic.IComparer<UnityEngine.Material> arg2 = (System.Collections.Generic.IComparer<UnityEngine.Material>)ToLua.ToObject(L, 4);
				obj.Sort(arg0, arg1, arg2);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: System.Collections.Generic.List<UnityEngine.Material>.Sort");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ToArray(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			UnityEngine.Material[] o = obj.ToArray();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int TrimExcess(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			obj.TrimExcess();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int TrueForAll(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			System.Predicate<UnityEngine.Material> arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (System.Predicate<UnityEngine.Material>)ToLua.CheckObject(L, 2, typeof(System.Predicate<UnityEngine.Material>));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(System.Predicate<UnityEngine.Material>), func) as System.Predicate<UnityEngine.Material>;
			}

			bool o = obj.TrueForAll(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Item(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			UnityEngine.Material o = obj[arg0];
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Item(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.Material>));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			UnityEngine.Material arg1 = (UnityEngine.Material)ToLua.CheckUnityObject(L, 3, typeof(UnityEngine.Material));
			obj[arg0] = arg1;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Capacity(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)o;
			int ret = obj.Capacity;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Capacity on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Count(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)o;
			int ret = obj.Count;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Count on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Capacity(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			System.Collections.Generic.List<UnityEngine.Material> obj = (System.Collections.Generic.List<UnityEngine.Material>)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.Capacity = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Capacity on a nil value" : e.Message);
		}
	}
}

