//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class TimeCostTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(TimeCostType), typeof(System.Object));
		L.RegFunction("New", _CreateTimeCostType);
		L.RegFunction("__tostring", Lua_ToString);
		L.RegVar("LoadingLoad", get_LoadingLoad, set_LoadingLoad);
		L.RegVar("NullSceneLoad", get_NullSceneLoad, set_NullSceneLoad);
		L.RegVar("SaceneAssetsLoad", get_SaceneAssetsLoad, set_SaceneAssetsLoad);
		L.RegVar("InstantiateAssets", get_InstantiateAssets, set_InstantiateAssets);
		L.RegVar("CreateSceneUI", get_CreateSceneUI, set_CreateSceneUI);
		L.RegVar("PiaoZiMode", get_PiaoZiMode, set_PiaoZiMode);
		L.RegVar("InitData", get_InitData, set_InitData);
		L.RegVar("UIPrefabPool", get_UIPrefabPool, set_UIPrefabPool);
		L.RegVar("LevelSysEnter", get_LevelSysEnter, set_LevelSysEnter);
		L.RegVar("ClearData", get_ClearData, set_ClearData);
		L.RegVar("StartLevel", get_StartLevel, set_StartLevel);
		L.RegVar("One", get_One, set_One);
		L.RegVar("Two", get_Two, set_Two);
		L.RegVar("Three", get_Three, set_Three);
		L.RegVar("Four", get_Four, set_Four);
		L.RegVar("Five", get_Five, set_Five);
		L.RegVar("Six", get_Six, set_Six);
		L.RegVar("Seven", get_Seven, set_Seven);
		L.RegVar("Eight", get_Eight, set_Eight);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateTimeCostType(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				TimeCostType obj = new TimeCostType();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: TimeCostType.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LoadingLoad(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, TimeCostType.LoadingLoad);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NullSceneLoad(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, TimeCostType.NullSceneLoad);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SaceneAssetsLoad(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, TimeCostType.SaceneAssetsLoad);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InstantiateAssets(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, TimeCostType.InstantiateAssets);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CreateSceneUI(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, TimeCostType.CreateSceneUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PiaoZiMode(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, TimeCostType.PiaoZiMode);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InitData(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, TimeCostType.InitData);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UIPrefabPool(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, TimeCostType.UIPrefabPool);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LevelSysEnter(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, TimeCostType.LevelSysEnter);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ClearData(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, TimeCostType.ClearData);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_StartLevel(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, TimeCostType.StartLevel);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_One(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, TimeCostType.One);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Two(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, TimeCostType.Two);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Three(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, TimeCostType.Three);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Four(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, TimeCostType.Four);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Five(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, TimeCostType.Five);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Six(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, TimeCostType.Six);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Seven(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, TimeCostType.Seven);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Eight(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, TimeCostType.Eight);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LoadingLoad(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			TimeCostType.LoadingLoad = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_NullSceneLoad(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			TimeCostType.NullSceneLoad = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_SaceneAssetsLoad(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			TimeCostType.SaceneAssetsLoad = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_InstantiateAssets(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			TimeCostType.InstantiateAssets = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CreateSceneUI(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			TimeCostType.CreateSceneUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_PiaoZiMode(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			TimeCostType.PiaoZiMode = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_InitData(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			TimeCostType.InitData = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_UIPrefabPool(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			TimeCostType.UIPrefabPool = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LevelSysEnter(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			TimeCostType.LevelSysEnter = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ClearData(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			TimeCostType.ClearData = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_StartLevel(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			TimeCostType.StartLevel = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_One(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			TimeCostType.One = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Two(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			TimeCostType.Two = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Three(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			TimeCostType.Three = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Four(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			TimeCostType.Four = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Five(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			TimeCostType.Five = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Six(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			TimeCostType.Six = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Seven(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			TimeCostType.Seven = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Eight(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			TimeCostType.Eight = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

