//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UIAnchor_SideWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UIAnchor.Side));
		L.RegVar("BottomLeft", get_BottomLeft, null);
		L.RegVar("Left", get_Left, null);
		L.RegVar("TopLeft", get_TopLeft, null);
		L.RegVar("Top", get_Top, null);
		L.RegVar("TopRight", get_TopRight, null);
		L.RegVar("Right", get_Right, null);
		L.RegVar("BottomRight", get_BottomRight, null);
		L.RegVar("Bottom", get_Bottom, null);
		L.RegVar("Center", get_Center, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BottomLeft(IntPtr L)
	{
		ToLua.Push(L, UIAnchor.Side.BottomLeft);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Left(IntPtr L)
	{
		ToLua.Push(L, UIAnchor.Side.Left);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TopLeft(IntPtr L)
	{
		ToLua.Push(L, UIAnchor.Side.TopLeft);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Top(IntPtr L)
	{
		ToLua.Push(L, UIAnchor.Side.Top);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TopRight(IntPtr L)
	{
		ToLua.Push(L, UIAnchor.Side.TopRight);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Right(IntPtr L)
	{
		ToLua.Push(L, UIAnchor.Side.Right);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BottomRight(IntPtr L)
	{
		ToLua.Push(L, UIAnchor.Side.BottomRight);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Bottom(IntPtr L)
	{
		ToLua.Push(L, UIAnchor.Side.Bottom);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Center(IntPtr L)
	{
		ToLua.Push(L, UIAnchor.Side.Center);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UIAnchor.Side o = (UIAnchor.Side)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

