//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class YX_APIManageWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(YX_APIManage), typeof(Singleton<YX_APIManage>));
		L.RegFunction("Awake", Awake);
		L.RegFunction("setHallTimer", setHallTimer);
		L.RegFunction("setGameTimer", setGameTimer);
		L.RegFunction("Update", Update);
		L.RegFunction("InitPlugins", InitPlugins);
		L.RegFunction("WeiXinLogin", WeiXinLogin);
		L.RegFunction("WeiXinShare", WeiXinShare);
		L.RegFunction("QQLogin", QQLogin);
		L.RegFunction("YX_IsEnableBattery", YX_IsEnableBattery);
		L.RegFunction("YX_GetPhoneStreng", YX_GetPhoneStreng);
		L.RegFunction("onPluginsInitFinsh", onPluginsInitFinsh);
		L.RegFunction("onWeiXinLoginCallBack", onWeiXinLoginCallBack);
		L.RegFunction("onQQLoginCallBack", onQQLoginCallBack);
		L.RegFunction("onCopyCallBack", onCopyCallBack);
		L.RegFunction("onCopy", onCopy);
		L.RegFunction("getCopyCallBack", getCopyCallBack);
		L.RegFunction("getCopy", getCopy);
		L.RegFunction("onPhoneBattery", onPhoneBattery);
		L.RegFunction("onPhoneSignal", onPhoneSignal);
		L.RegFunction("startIAppPay", startIAppPay);
		L.RegFunction("onIAppPayCallBack", onIAppPayCallBack);
		L.RegFunction("onGetStoragePath", onGetStoragePath);
		L.RegFunction("read", read);
		L.RegFunction("deleteFile", deleteFile);
		L.RegFunction("nowTime", nowTime);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", Lua_ToString);
		L.RegVar("delegateNetHallCallBack", get_delegateNetHallCallBack, set_delegateNetHallCallBack);
		L.RegVar("delegateNetGameCallBack", get_delegateNetGameCallBack, set_delegateNetGameCallBack);
		L.RegVar("batteryCallBack", get_batteryCallBack, set_batteryCallBack);
		L.RegVar("delegateLoginResp", get_delegateLoginResp, set_delegateLoginResp);
		L.RegVar("oncopyCallback", get_oncopyCallback, set_oncopyCallback);
		L.RegVar("getcopyCallback", get_getcopyCallback, set_getcopyCallback);
		L.RegVar("delegateIAppPayResp", get_delegateIAppPayResp, set_delegateIAppPayResp);
		L.RegVar("CurrentReachability", get_CurrentReachability, set_CurrentReachability);
		L.RegFunction("DelegateNetHallCallBack", YX_APIManage_DelegateNetHallCallBack);
		L.RegFunction("DelegateNetGameCallBack", YX_APIManage_DelegateNetGameCallBack);
		L.RegFunction("DelegateLoginResp", YX_APIManage_DelegateLoginResp);
		L.RegFunction("onCopyCall", YX_APIManage_onCopyCall);
		L.RegFunction("getCopyCall", YX_APIManage_getCopyCall);
		L.RegFunction("DelegateIAppPayResp", YX_APIManage_DelegateIAppPayResp);
		L.RegFunction("BatteryCallBack", YX_APIManage_BatteryCallBack);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Awake(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			obj.Awake();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setHallTimer(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			YX_APIManage.DelegateNetHallCallBack arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (YX_APIManage.DelegateNetHallCallBack)ToLua.CheckObject(L, 2, typeof(YX_APIManage.DelegateNetHallCallBack));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(YX_APIManage.DelegateNetHallCallBack), func) as YX_APIManage.DelegateNetHallCallBack;
			}

			obj.setHallTimer(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setGameTimer(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			YX_APIManage.DelegateNetGameCallBack arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (YX_APIManage.DelegateNetGameCallBack)ToLua.CheckObject(L, 2, typeof(YX_APIManage.DelegateNetGameCallBack));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(YX_APIManage.DelegateNetGameCallBack), func) as YX_APIManage.DelegateNetGameCallBack;
			}

			obj.setGameTimer(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Update(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			obj.Update();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InitPlugins(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.InitPlugins(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int WeiXinLogin(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			YX_APIManage.DelegateLoginResp arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (YX_APIManage.DelegateLoginResp)ToLua.CheckObject(L, 2, typeof(YX_APIManage.DelegateLoginResp));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(YX_APIManage.DelegateLoginResp), func) as YX_APIManage.DelegateLoginResp;
			}

			obj.WeiXinLogin(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int WeiXinShare(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 7);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			string arg2 = ToLua.CheckString(L, 4);
			string arg3 = ToLua.CheckString(L, 5);
			string arg4 = ToLua.CheckString(L, 6);
			string arg5 = ToLua.CheckString(L, 7);
			obj.WeiXinShare(arg0, arg1, arg2, arg3, arg4, arg5);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int QQLogin(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			YX_APIManage.DelegateLoginResp arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (YX_APIManage.DelegateLoginResp)ToLua.CheckObject(L, 2, typeof(YX_APIManage.DelegateLoginResp));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(YX_APIManage.DelegateLoginResp), func) as YX_APIManage.DelegateLoginResp;
			}

			obj.QQLogin(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int YX_IsEnableBattery(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.YX_IsEnableBattery(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int YX_GetPhoneStreng(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			obj.YX_GetPhoneStreng();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int onPluginsInitFinsh(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			string arg0 = ToLua.CheckString(L, 2);
			obj.onPluginsInitFinsh(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int onWeiXinLoginCallBack(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			string arg0 = ToLua.CheckString(L, 2);
			obj.onWeiXinLoginCallBack(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int onQQLoginCallBack(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			string arg0 = ToLua.CheckString(L, 2);
			obj.onQQLoginCallBack(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int onCopyCallBack(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			string arg0 = ToLua.CheckString(L, 2);
			obj.onCopyCallBack(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int onCopy(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			string arg0 = ToLua.CheckString(L, 2);
			YX_APIManage.onCopyCall arg1 = null;
			LuaTypes funcType3 = LuaDLL.lua_type(L, 3);

			if (funcType3 != LuaTypes.LUA_TFUNCTION)
			{
				 arg1 = (YX_APIManage.onCopyCall)ToLua.CheckObject(L, 3, typeof(YX_APIManage.onCopyCall));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 3);
				arg1 = DelegateFactory.CreateDelegate(typeof(YX_APIManage.onCopyCall), func) as YX_APIManage.onCopyCall;
			}

			obj.onCopy(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getCopyCallBack(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			string arg0 = ToLua.CheckString(L, 2);
			obj.getCopyCallBack(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getCopy(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			YX_APIManage.getCopyCall arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (YX_APIManage.getCopyCall)ToLua.CheckObject(L, 2, typeof(YX_APIManage.getCopyCall));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(YX_APIManage.getCopyCall), func) as YX_APIManage.getCopyCall;
			}

			obj.getCopy(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int onPhoneBattery(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			string arg0 = ToLua.CheckString(L, 2);
			obj.onPhoneBattery(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int onPhoneSignal(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			string arg0 = ToLua.CheckString(L, 2);
			obj.onPhoneSignal(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int startIAppPay(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			string arg0 = ToLua.CheckString(L, 2);
			YX_APIManage.DelegateIAppPayResp arg1 = null;
			LuaTypes funcType3 = LuaDLL.lua_type(L, 3);

			if (funcType3 != LuaTypes.LUA_TFUNCTION)
			{
				 arg1 = (YX_APIManage.DelegateIAppPayResp)ToLua.CheckObject(L, 3, typeof(YX_APIManage.DelegateIAppPayResp));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 3);
				arg1 = DelegateFactory.CreateDelegate(typeof(YX_APIManage.DelegateIAppPayResp), func) as YX_APIManage.DelegateIAppPayResp;
			}

			obj.startIAppPay(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int onIAppPayCallBack(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			string arg0 = ToLua.CheckString(L, 2);
			obj.onIAppPayCallBack(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int onGetStoragePath(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			string o = obj.onGetStoragePath();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int read(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			string arg0 = ToLua.CheckString(L, 2);
			string o = obj.read(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int deleteFile(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			string arg0 = ToLua.CheckString(L, 2);
			obj.deleteFile(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int nowTime(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			YX_APIManage obj = (YX_APIManage)ToLua.CheckObject(L, 1, typeof(YX_APIManage));
			long o = obj.nowTime();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_delegateNetHallCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			YX_APIManage obj = (YX_APIManage)o;
			YX_APIManage.DelegateNetHallCallBack ret = obj.delegateNetHallCallBack;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index delegateNetHallCallBack on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_delegateNetGameCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			YX_APIManage obj = (YX_APIManage)o;
			YX_APIManage.DelegateNetGameCallBack ret = obj.delegateNetGameCallBack;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index delegateNetGameCallBack on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_batteryCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			YX_APIManage obj = (YX_APIManage)o;
			YX_APIManage.BatteryCallBack ret = obj.batteryCallBack;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index batteryCallBack on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_delegateLoginResp(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			YX_APIManage obj = (YX_APIManage)o;
			YX_APIManage.DelegateLoginResp ret = obj.delegateLoginResp;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index delegateLoginResp on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_oncopyCallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			YX_APIManage obj = (YX_APIManage)o;
			YX_APIManage.onCopyCall ret = obj.oncopyCallback;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index oncopyCallback on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_getcopyCallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			YX_APIManage obj = (YX_APIManage)o;
			YX_APIManage.getCopyCall ret = obj.getcopyCallback;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index getcopyCallback on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_delegateIAppPayResp(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			YX_APIManage obj = (YX_APIManage)o;
			YX_APIManage.DelegateIAppPayResp ret = obj.delegateIAppPayResp;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index delegateIAppPayResp on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CurrentReachability(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			YX_APIManage obj = (YX_APIManage)o;
			UnityEngine.NetworkReachability ret = obj.CurrentReachability;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index CurrentReachability on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_delegateNetHallCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			YX_APIManage obj = (YX_APIManage)o;
			YX_APIManage.DelegateNetHallCallBack arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (YX_APIManage.DelegateNetHallCallBack)ToLua.CheckObject(L, 2, typeof(YX_APIManage.DelegateNetHallCallBack));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(YX_APIManage.DelegateNetHallCallBack), func) as YX_APIManage.DelegateNetHallCallBack;
			}

			obj.delegateNetHallCallBack = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index delegateNetHallCallBack on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_delegateNetGameCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			YX_APIManage obj = (YX_APIManage)o;
			YX_APIManage.DelegateNetGameCallBack arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (YX_APIManage.DelegateNetGameCallBack)ToLua.CheckObject(L, 2, typeof(YX_APIManage.DelegateNetGameCallBack));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(YX_APIManage.DelegateNetGameCallBack), func) as YX_APIManage.DelegateNetGameCallBack;
			}

			obj.delegateNetGameCallBack = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index delegateNetGameCallBack on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_batteryCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			YX_APIManage obj = (YX_APIManage)o;
			YX_APIManage.BatteryCallBack arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (YX_APIManage.BatteryCallBack)ToLua.CheckObject(L, 2, typeof(YX_APIManage.BatteryCallBack));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(YX_APIManage.BatteryCallBack), func) as YX_APIManage.BatteryCallBack;
			}

			obj.batteryCallBack = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index batteryCallBack on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_delegateLoginResp(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			YX_APIManage obj = (YX_APIManage)o;
			YX_APIManage.DelegateLoginResp arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (YX_APIManage.DelegateLoginResp)ToLua.CheckObject(L, 2, typeof(YX_APIManage.DelegateLoginResp));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(YX_APIManage.DelegateLoginResp), func) as YX_APIManage.DelegateLoginResp;
			}

			obj.delegateLoginResp = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index delegateLoginResp on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_oncopyCallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			YX_APIManage obj = (YX_APIManage)o;
			YX_APIManage.onCopyCall arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (YX_APIManage.onCopyCall)ToLua.CheckObject(L, 2, typeof(YX_APIManage.onCopyCall));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(YX_APIManage.onCopyCall), func) as YX_APIManage.onCopyCall;
			}

			obj.oncopyCallback = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index oncopyCallback on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_getcopyCallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			YX_APIManage obj = (YX_APIManage)o;
			YX_APIManage.getCopyCall arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (YX_APIManage.getCopyCall)ToLua.CheckObject(L, 2, typeof(YX_APIManage.getCopyCall));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(YX_APIManage.getCopyCall), func) as YX_APIManage.getCopyCall;
			}

			obj.getcopyCallback = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index getcopyCallback on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_delegateIAppPayResp(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			YX_APIManage obj = (YX_APIManage)o;
			YX_APIManage.DelegateIAppPayResp arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (YX_APIManage.DelegateIAppPayResp)ToLua.CheckObject(L, 2, typeof(YX_APIManage.DelegateIAppPayResp));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(YX_APIManage.DelegateIAppPayResp), func) as YX_APIManage.DelegateIAppPayResp;
			}

			obj.delegateIAppPayResp = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index delegateIAppPayResp on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CurrentReachability(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			YX_APIManage obj = (YX_APIManage)o;
			UnityEngine.NetworkReachability arg0 = (UnityEngine.NetworkReachability)ToLua.CheckObject(L, 2, typeof(UnityEngine.NetworkReachability));
			obj.CurrentReachability = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index CurrentReachability on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int YX_APIManage_DelegateNetHallCallBack(IntPtr L)
	{
		try
		{
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);
			Delegate arg1 = DelegateFactory.CreateDelegate(typeof(YX_APIManage.DelegateNetHallCallBack), func);
			ToLua.Push(L, arg1);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int YX_APIManage_DelegateNetGameCallBack(IntPtr L)
	{
		try
		{
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);
			Delegate arg1 = DelegateFactory.CreateDelegate(typeof(YX_APIManage.DelegateNetGameCallBack), func);
			ToLua.Push(L, arg1);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int YX_APIManage_DelegateLoginResp(IntPtr L)
	{
		try
		{
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);
			Delegate arg1 = DelegateFactory.CreateDelegate(typeof(YX_APIManage.DelegateLoginResp), func);
			ToLua.Push(L, arg1);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int YX_APIManage_onCopyCall(IntPtr L)
	{
		try
		{
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);
			Delegate arg1 = DelegateFactory.CreateDelegate(typeof(YX_APIManage.onCopyCall), func);
			ToLua.Push(L, arg1);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int YX_APIManage_getCopyCall(IntPtr L)
	{
		try
		{
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);
			Delegate arg1 = DelegateFactory.CreateDelegate(typeof(YX_APIManage.getCopyCall), func);
			ToLua.Push(L, arg1);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int YX_APIManage_DelegateIAppPayResp(IntPtr L)
	{
		try
		{
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);
			Delegate arg1 = DelegateFactory.CreateDelegate(typeof(YX_APIManage.DelegateIAppPayResp), func);
			ToLua.Push(L, arg1);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int YX_APIManage_BatteryCallBack(IntPtr L)
	{
		try
		{
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);
			Delegate arg1 = DelegateFactory.CreateDelegate(typeof(YX_APIManage.BatteryCallBack), func);
			ToLua.Push(L, arg1);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

