//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class YX_MoblieAPIWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(YX_MoblieAPI), typeof(Singleton<YX_MoblieAPI>));
		L.RegFunction("shake", shake);
		L.RegFunction("GetCenterPicture", GetCenterPicture);
		L.RegFunction("CaptureByRect", CaptureByRect);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", Lua_ToString);
		L.RegVar("onfinishtx", get_onfinishtx, set_onfinishtx);
		L.RegFunction("onFinishTx", YX_MoblieAPI_onFinishTx);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int shake(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			YX_MoblieAPI obj = (YX_MoblieAPI)ToLua.CheckObject(L, 1, typeof(YX_MoblieAPI));
			obj.shake();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCenterPicture(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			YX_MoblieAPI obj = (YX_MoblieAPI)ToLua.CheckObject(L, 1, typeof(YX_MoblieAPI));
			string arg0 = ToLua.CheckString(L, 2);
			obj.GetCenterPicture(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CaptureByRect(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			YX_MoblieAPI obj = (YX_MoblieAPI)ToLua.CheckObject(L, 1, typeof(YX_MoblieAPI));
			string arg0 = ToLua.CheckString(L, 2);
			UITexture arg1 = (UITexture)ToLua.CheckUnityObject(L, 3, typeof(UITexture));
			System.Collections.IEnumerator o = obj.CaptureByRect(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onfinishtx(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			YX_MoblieAPI obj = (YX_MoblieAPI)o;
			YX_MoblieAPI.onFinishTx ret = obj.onfinishtx;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index onfinishtx on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onfinishtx(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			YX_MoblieAPI obj = (YX_MoblieAPI)o;
			YX_MoblieAPI.onFinishTx arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (YX_MoblieAPI.onFinishTx)ToLua.CheckObject(L, 2, typeof(YX_MoblieAPI.onFinishTx));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(YX_MoblieAPI.onFinishTx), func) as YX_MoblieAPI.onFinishTx;
			}

			obj.onfinishtx = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index onfinishtx on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int YX_MoblieAPI_onFinishTx(IntPtr L)
	{
		try
		{
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);
			Delegate arg1 = DelegateFactory.CreateDelegate(typeof(YX_MoblieAPI.onFinishTx), func);
			ToLua.Push(L, arg1);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

